default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456
  pool: 5

development:
  <<: *default
  database: caio_ecommerce_application_development

test:
  <<: *default
  database: caio_ecommerce_application_test

production:
  <<: *default
  database: caio_ecommerce_application_production
  # You can also provide SSL configuration here for Heroku if needed:
  # sslmode: require